Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/data/srlab1/jmears/srlab/scripts/sc_utils.R': No such file or directory
Execution halted
